expressions:
  - ">_<"
  - ":3"
  - "ʕʘ‿ʘʔ"
  - ":D"
  - "._."
  - ";3"
  - "xD"
  - "ㅇㅅㅇ"
  - "(人◕ω◕)"
  - ">_>"
  - "ÙωÙ"
  - "UwU"
  - "OwO"
  - ":P"
  - "(◠‿◠✿)"
  - "^_^"
  - ";_;"
  - "XDDD"
  - "x3"
  - "(• o •)"
  - "<_<"
use_perms: false