name: Owoifier
description: owoifier owoifies your server!
main: xyz.nkomarn.owoifier.Owoifier
version: '1.3.2'
author: TechToolbox (@nkomarn), M2Shawning
website: https://nkomarn.xyz, https://github.com/m2shawning
api-version: '1.13'
commands:
  owo:
    description: Toggle the use of owo mode
    usage: /owo
permissions:
  owoifier.use:
    description: Enables owoifier for people with this permission
    default: false
    children:
      owoifier.use.chat: true
      owoifier.use.sign: true
  owoifier.use.chat:
    description: Enables owoifier on only chat for people with this permission
    default: false
  owoifier.use.sign:
    description: Enables owoifier on only signs for people with this permission
    default: false